version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  practica8:
    container_name: practica8
    image: andreaflores/practica8:latest
    build:
      dockerfile: Dockerfile
      context: ./Cliente
    ports:
      - '8080:8080'
  
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'practica8'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'

  volumes:
    my-datavolume: